Html home
TransEmpregos/transempregos-portal pull request #25
Opened 2017-01-05 17:25 UTC by lleitep3

Layout responsivo da página Home

2017-01-05 22:23 UTC, giggio requested changes
Em geral está bem bom, falta uns detalhes. Anotei os arquivos e mais alguns aqui abaixo:

 * Senti falta de um html mais semântico, com h1, h2, h3, etc...
 * O nome das imagens dos parceiros deveria ser semântico também, em vez de parceiro1, parceiro2, etc.
 * Em vários lugares aparece `recruter`, faltou o `i` de `recruiter`. Olhar nomes de arquivos, rotas, etc.
 * O desenho do laerte está em 2 formatos: png e svg. Precisa escolher um e remover o outro.
 * A imagem do adesivo de diversidade está presente, mas não é usada em nenhum lugar.
 * Parte do scss global está no diretório `scss` e outra parte na home. O de variables, por exemplo, não devia estar no diretório `scss` também?

2017-01-05 22:23 UTC, giggio commented on public/app/app.component.scss
>      color: red
Tinha que ter tirado isso, né?

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +            </ul>
Faltou o logo da Lambda3.

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +            <a href="javascript:void(0);"
Isso não é um link, ele não navega. Trocar de `<a` pra outra coisa, tipo `<span`, e remover o `href`. E no home.component.scss usar `cursor: pointer` pra aparecer corretamente.

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +                    <label for="location">Localização da vaga</label>
Faltou o ícone à esquerda da palavra `Localização`.

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +    <section class="description-area relative col-xs-12">
Faltaram as 3 abas de "O que é o transempregos", "Cadastre seu Currículo" e "Perguntas frequentes".

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +            <img class="img-description" src="/dist/public/images/Desenho_Laerte_Transempregos.png">
A imagem some quando está no celular (responsivo).

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +        <div class="general-board-depositions">
No celular, quando em responsivo, a imagem de fundo fica totalmente perdida no fundo, não dá pra entender o que é.

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +            <ul>
No responsivo (celular) os logos estão embolados, o ideal é ficar um em cima do outro, ou 2 um do lado do outro, por linha.

2017-01-05 22:23 UTC, giggio commented on public/app/home/home.component.html
> +            <button type="button" class="btn btn-secondary btn-lg">quero ser parceiro</button>
No responsivo (celular) o botão não fica centralizado, está alinhado à esquerda.

2017-01-05 22:23 UTC, giggio commented on public/app/app-routing.module.ts
> +  { path: 'login/recruter', component: LoginRecruterComponent },
Deveria ser `recruiter`, está faltando o `i`.

2017-01-05 22:23 UTC, giggio commented on public/app/app.component.html
> +                                    <a href="#" class="dropdown-item">Recrutador(a)</a>
Isso devia usar um router link para `/login/recruiter`.

2017-01-09 14:42 UTC, lleitep3 commented on public/app/app.component.scss
>      color: red
verdade

2017-01-09 22:38 UTC, giggio approved these changes

2017-01-10 01:31 UTC, merged