Start registration of new resumes
TransEmpregos/transempregos-portal pull request #55
Opened 2017-02-10 22:49 UTC by thiagoholder

2017-02-10 23:48 UTC, giggio requested changes
@thiagoholder está com conflito. Resolve, pfv.

2017-02-12 07:14 UTC, thiagoholder commented
Giovanni eu corrigi no meu ambiente, fiz o rebase para minha master, mas não consigo enviar o PUSH --force upstream. Diz que não tenho acesso.

2017-02-12 07:55 UTC, thiagoholder commented
Pronto, agora foi :) Conflitos resolvidos

2017-02-13 00:40 UTC, giggio commented
@thiagoholder tem testes quebrando, olha a build.

2023-01-27 02:31 UTC, closed without merging